### ISSUE TITLE
[QUESTION] Will the app purge messages and media as well?

### ISSUE THREAD

**Issue by lzc256** [yaky-dev/synapse-room-cleaner#1]
I had deployed a telegram bridge on my homeserver but now I don’t need it anymore. But after logging out, the room data weren’t automatically deleted. Commands like `clean-rooms` didn’t work as well. The bridge have consumed me 300mb database storage and 3.5g disk usage, which makes me desperate to purge all messages and media files.

I found this project, tried to list rooms and I am glad to find that there are 95 rooms that can be deleted. However I wonder if this app will delete all messages and media files as well?

Thanks a lot for your reply!

**Comment by yaky-dev** [comment]
Hey!
First, I am glad you found my little project useful.
As far as I know, deleting rooms does delete all associated messages, and, thus, references to files, but not the media files themselves. Media is stored in a directory specified in homeserver.yaml, and I had to delete files manually before.
BTW, if you liked Synapse Room Cleaner, check out my next iteration of it, Simple Synapse Admin (https://github.com/yaky-dev/simple-synapse-admin), it lets you manage users too (reset passwords, delete, etc), and access tokens, if you use those.
